### Create user
POST http://localhost:8000/auth/signup
content-type: application/json

{
    "email":"test@test.com",
    "password":"test123"
}

### Signin user
POST http://localhost:8000/auth/signin
content-type: application/json

{
    "email":"admin@admin.com",
    "password":"test123"
}

### Signout user
POST http://localhost:8000/auth/signout

### Get current user
GET http://localhost:8000/auth/whoami

### Find specific user
GET http://localhost:8000/auth/14

### Find specific user with given email
GET http://localhost:8000/auth?email=test@test.com

### Find all users
GET http://localhost:8000/auth

### Delete specific user
DELETE http://localhost:8000/auth/4

### Update user
PATCH http://localhost:8000/auth/14
content-type: application/json 

{
    "email":"test@test.com",
    "password":"test123"
}
